package irq

const (
	SERVICE_CLASS_REGS = 0x1000

	SERVICE_STORE_REGS = SERVICE_CLASS_REGS | 1
	SERVICE_SCHEDULE_USER = SERVICE_CLASS_REGS | 2
)

const (
	SERVICE_OK = 0x1000
	SERVICE_IRQ_NOTE = 0x0100
	SERVICE_ERR = 0x2000
	SERVICE_ERR_BAD_CALL = SERVICE_ERR | 1
)